apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - image: lloesche/valheim-server:latest
          name: vailheim-server
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-secrets
          ports:
            {{- range $i, $gamePortMapping := .Values.networking.portMapping }}
            - name: {{ $gamePortMapping.name }}
              containerPort: {{ $gamePortMapping.containerPort }}
              hostPort: {{ $gamePortMapping.exposedPort }}
              protocol: UDP
            {{- end }}
          {{- if .Values.storage.enabled }}
          volumeMounts:
            - mountPath: /config
              name: gamefiles
          {{- end }}
          {{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12}}
          {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: gamefiles
          {{- if .Values.storage.hostVolume.enabled }}
          hostPath:
            path: {{ .Values.storage.path }}
            type: Directory
          {{- end}}
          {{- if .Values.storage.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{.Values.storage.pvc.name}}
            readOnly: false
          {{- end}}
  {{- end }}