apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  ports:
  {{- range $i, $gamePortMapping := .Values.networking.portMapping }}
    - name: {{ $gamePortMapping.name }}
      targetPort: {{ $gamePortMapping.exposedPort }}
      port: {{ $gamePortMapping.exposedPort }}
      protocol: UDP
  {{- end }}
  type: {{ .Values.networking.serviceType }}
  selector:
    app: {{.Release.Name}}
