apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  ports:
  {{- range $key, $val := .Values.games }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  type: {{ .Values.networking.serviceType }}
  selector:
    app: {{.Release.Name}}
