{{- if .Values.storage.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.storage.pvc.name}}
spec:
  accessModes:
    - {{.Values.storage.pvc.accessMode}}
  resources:
    requests:
      storage: {{.Values.storage.pvc.resources.requests.storage}}
  storageClassName: {{.Values.storage.pvc.storageClassName}}
{{- end}}